### ISSUE TITLE
EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by riderx** [rexxars/get-latest-version#10] opened 2023-03-05 09:40 UTC
One of the user of my CLI got this issue:

```
Need to install the following packages:
  @capgo/cli@3.5.6
Ok to proceed? (y) y
⚠️  This command is deprecated, use "npx @capgo/cli bundle upload" instead ⚠️
node:fs:723
  handleErrorFromBinding(ctx);
  ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at Conf.addFile (/Users/fabioberger/.npm/_npx/cbe5d2f7487966de/node_modules/@pnpm/npm-conf/lib/conf.js:41:24)
    at module.exports (/Users/fabioberger/.npm/_npx/cbe5d2f7487966de/node_modules/@pnpm/npm-conf/index.js:28:9)
    at getRegistryAuthToken (/Users/fabioberger/.npm/_npx/cbe5d2f7487966de/node_modules/registry-auth-token/index.js:24:7)
    at getLatestVersion (/Users/fabioberger/.npm/_npx/cbe5d2f7487966de/node_modules/get-latest-version/src/index.js:40:36)
    at /Users/fabioberger/.npm/_npx/cbe5d2f7487966de/node_modules/@capgo/cli/dist/index.js:2:8023
    at Generator.next (<anonymous>)
    at /Users/fabioberger/.npm/_npx/cbe5d2f7487966de/node_modules/@capgo/cli/dist/index.js:2:7749 {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```
I tried to investigate but i don't understand why that can fail, maybe you can understand it better than me.

**Comment by rexxars** [comment] 2023-03-05 21:41
Thanks for reporting - fixed in v5.0.1

**Closed** 2023-03-05 21:40 UTC

**Comment by rexxars** [comment] 2023-03-05 21:42
For reference:

It looks like the user has/had an `npmrc` that the `@pnpm/npm-conf` module assumes is a file, but is actually a directory. This case is now silently suppressed by this module, but in case you want to let your user know the cause; there it is :)

**Comment by riderx** [comment] 2023-03-06 10:02
thanks a lot 🙏

**Comment by riderx** [comment] 2023-03-06 16:04
@rexxars my user said :
Indeed I use npmrc because I need to have different npm registries depending on the project I'm working on (one of them will use a private registry).

https://www.npmjs.com/package/npmrc
So that because of this he got the issue
